//
//  OpenAIChatUsage.swift
//
//
//  Created by Lou Zell on 9/19/24.
//

import Foundation

/// Docstrings from:
/// https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage
nonisolated public struct OpenAIChatUsage: Decodable, Sendable {
    /// Number of tokens in the generated completion.
    public let completionTokens: Int?

    /// Number of tokens in the prompt.
    public let promptTokens: Int?

    /// Total number of tokens used in the request (prompt + completion).
    public let totalTokens: Int?

    /// Breakdown of tokens used in a completion.
    public let completionTokensDetails: Details?

    /// Breakdown of tokens used in the prompt (e.g. how many were served from
    /// the provider's prompt cache).
    public let promptTokensDetails: PromptTokensDetails?

    private enum CodingKeys: String, CodingKey {
        case completionTokens = "completion_tokens"
        case promptTokens = "prompt_tokens"
        case totalTokens = "total_tokens"
        case completionTokensDetails = "completion_tokens_details"
        case promptTokensDetails = "prompt_tokens_details"
    }
}

// MARK: -
extension OpenAIChatUsage {
    nonisolated public struct Details: Decodable, Sendable {
        /// Tokens generated by the model for reasoning.
        public let reasoningTokens: Int?

        private enum CodingKeys: String, CodingKey {
            case reasoningTokens = "reasoning_tokens"
        }
    }

    nonisolated public struct PromptTokensDetails: Decodable, Sendable {
        /// Number of prompt tokens served from the provider's prompt cache.
        public let cachedTokens: Int?

        private enum CodingKeys: String, CodingKey {
            case cachedTokens = "cached_tokens"
        }
    }
}
